name: Check formatting
on:
  release:
    types:
      - released
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install modules
        run: yarn
      - name: Check formatting
        run: |
          yarn format:check
