name: Take Screenshots
on:
  release:
    types:
      - released
  workflow_dispatch:
  push:
  
jobs:
  export_screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install modules
        run: |
          yarn
          sudo apt install chromium-browser xvfb
      - name: Build extensions
        run: |
          yarn build production
          yarn package
      - name: Try screenshotting
        run: |
          yarn sc