name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: c-hive/gha-yarn-cache@v1
    - name: Install modules
      run: |
        yarn
        git checkout .
    - name: Run tests
      run: yarn test
